version: '3.8'

services:
  app:
    build: .
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: 5432
      POSTGRES_DB: db
      JSON_LOGS: true
    ports:
      - "9080:9080"
      - "8080:8080"
    depends_on:
      - "db"

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
